# USE 5G NUMEROLOGY 1

radar:
  fc: 3500000000.0    # Carrier frequency (Hz)
  NF: 8.0             # Receiver Noise Figure (dB)
  temperature: 290.0  # Temperature (K)
  H: 3                # Number of targets
  FAR: 0.000000001            # False alarm rate
  
ofdm:
  modulation: "BPSK"  # Modulation scheme (BPSK or QPSK)
  delta_f: 30000.0    # Subcarrier spacing (Hz)
  T_cp: 0.00000234    # Cyclic prefix duration (seconds)
  N_fft: 4096         # FFT size
  N: 3276             # Number of active subcarriers
  M: 256              # Number of OFDM symbols

periodogram:
  N_per: 8192         # Number of periodogram range bins
  M_per: 8192         # Number of periodogram doppler bins

targets:
  - distance: 20.0    # meters
    velocity: 0.0     # m/s
    rcs: 20.0         # radar cross section in dBsm

  - distance: 25.0    
    velocity: -50.0   
    rcs: 20.0          

  - distance: 30.0
    velocity: 0.0
    rcs: 20.0