# USE 5G NUMEROLOGY 1

radar:
  fc: 3500000000.0    # Carrier frequency (Hz)
  Ptx: 30.0           # Transmit power (dBm)
  G: 0.0             # Antenna gain (dBi)
  NF: 8.0             # Receiver Noise Figure (dB)
  temperature: 290.0  # Temperature (K)
  PFA: 0.00001           # Probability of False Alarm (PFA)
  
ofdm:
  modulation: "QPSK"  # Modulation scheme (BPSK or QPSK)
  delta_f: 30000.0    # Subcarrier spacing (Hz)
  T_cp: 0.00000234    # Cyclic prefix duration (seconds)
  N_fft: 4096         # FFT size
  N: 3275             # Number of active subcarriers
  M: 512              # Number of OFDM symbols

periodogram:
  configure: False
  N_per: 8192         # Number of periodogram range bins
  M_per: 8192         # Number of periodogram doppler bins
  window: "hamming"   #(options: "rect", "hamming", "bharris")

targets:
  - distance: 20.0    # meters
    velocity: 0.0     # m/s
    rcs: 20.0         # radar cross section in dBsm

  - distance: 25.0    
    velocity: -50.0   
    rcs: 20.0          

  - distance: 30.0
    velocity: 0.0
    rcs: 20.0        

  - distance: 35.0
    velocity: 40.0
    rcs: 20.0